# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src"
      dockerfile: "Services/Basket/Basket.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basket.api:dev"
    ports: []
    volumes:
    - "/Users/artyomdanielyan/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src/Services/Basket/Basket.API:/app:rw"
    - "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src"
      dockerfile: "Services/Catalog/CatalogAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CatalogAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/artyomdanielyan/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src/Services/Catalog/CatalogAPI:/app:rw"
    - "/Users/artyomdanielyan/Desktop/myProjcets/EShopMicroservices/src:/src:rw"
    working_dir: "/app"
